const SET_TOKEN = "SET_TOKEN";
const REQUEST_CHARACTERS = "REQUEST_CHARACTERS";
const INVALIDATE_CHARACTERS = "INVALIDATE_CHARACTERS";
const RECEIVE_CHARACTERS = "RECEIVE_CHARACTERS";
const URL_API = "http://localhost:3000/api";

export {SET_TOKEN, URL_API, REQUEST_CHARACTERS, RECEIVE_CHARACTERS, INVALIDATE_CHARACTERS}